resolver: nightly-2018-11-07

# due to functor-infix
allow-newer: true

packages:
  - 'ghc-primop'
  - 'ghc-dump-core'
  - 'ghc-dump-util'
  - 'ghc-grin'
  - 'lambda-grin'
#  - '../grin/grin'
  - location:
      git: https://github.com/grin-tech/grin
      commit: a73a94cfaf597f3a4239f4585d270915744dc8ba
    subdirs:
      - grin
    extra-dep: true

  - location:
      git: https://github.com/csabahruska/llvm-hs.git
      commit: 37aaa694d2f7907634f7af602d9aae125101db8d
    subdirs:
      - llvm-hs
    extra-dep: true


extra-deps:
  - monad-gen-0.3.0.1
  - functor-infix-0.0.5
  - megaparsec-6.5.0
  - neat-interpolation-0.3.2.2
  - set-extra-1.4.1
  - llvm-hs-pretty-0.6.1.0

flags:
  llvm-hs:
    shared-llvm: true

build:
  test-arguments:
    additional-args:
      - "--seed=11010"
