resolver: nightly-2018-11-07

# due to functor-infix
allow-newer: true

packages:
  - 'ghc-primop'
  - 'ghc-dump-core'
  - 'ghc-dump-util'
  - 'ghc-grin'
  - 'lambda-grin'
#  - '../grin/grin'
  - location:
      git: https://github.com/grin-tech/grin
      commit: 8b0c264a35caba335c662ae064d5b5d5a7e6214d
    subdirs:
      - grin
    extra-dep: true

  - location:
    # git: https://github.com/csabahruska/llvm-hs.git
      git: https://github.com/llvm-hs/llvm-hs
    # commit: 5e5feb5d125df3c789ef85ca344bced283b2fbaa
    # this sticks to llvm-7.0:
      commit: 3b4e35e1abd88f8f30400242503d7cb25f9be253
    subdirs:
      - llvm-hs
      - llvm-hs-pure
    extra-dep: true


extra-deps:
  - monad-gen-0.3.0.1
  - functor-infix-0.0.5
  - megaparsec-6.5.0
  - neat-interpolation-0.3.2.2
  - set-extra-1.4.1
  - llvm-hs-pretty-0.6.1.0

flags:
  llvm-hs:
    shared-llvm: true

build:
  test-arguments:
    additional-args:
      - "--seed=11010"
