resolver: nightly-2018-11-07

# due to functor-infix
allow-newer: true

packages:
  - 'ghc-dump-core'
  - 'ghc-dump-util'
  - 'ghc-grin'
  - 'lambda-grin'
#  - '../grin/grin'
  - location:
      git: https://github.com/grin-tech/grin
      commit: 05983c972880884780bf2c66324fd7da6a55841a
    subdirs:
      - grin
    extra-dep: true

  - location:
      git: https://github.com/llvm-hs/llvm-hs-pretty
      commit: 0d04346ea179e96797a284d094e44e538fbddcf2
    extra-dep: true


extra-deps:
  - monad-gen-0.3.0.1
  - functor-infix-0.0.5
  - megaparsec-6.5.0
  - neat-interpolation-0.3.2.2
  - set-extra-1.4.1

flags:
  llvm-hs:
    shared-llvm: true

build:
  test-arguments:
    additional-args:
      - "--seed=11010"
